log:
  debug: false
apis:
  grpc:
    address: "0.0.0.0:9000"
    tls:
      caFile: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/public/cert.crt"
      clientCertificateRequired: true
  http:
    address: "0.0.0.0:9001"
    tls:
      caFile: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/public/cert.crt"
      clientCertificateRequired: true
oauthClients:
  device:
    provider: "plgd"
    clientID: ""
    clientSecret: ""
    scopes: []
    authorizationURL: ""
    tokenURL: ""
    redirectURL: "" 
    http:
      maxIdleConns: 16
      maxConnsPerHost: 32
      maxIdleConnsPerHost: 16
      idleConnTimeout: 30s
      timeout: 10s
      tls:
        caFile: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
    ownerClaim: "sub"
  client:
    clientID: ""
    scopes: []
    authorizationURL: ""
    audience: ""
    redirectURL: ""
    http:
      maxIdleConns: 16
      maxConnsPerHost: 32
      maxIdleConnsPerHost: 16
      idleConnTimeout: 30s
      timeout: 10s
      tls:
        caFile: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
databases:
  mongoDB:
    uri: "mongodb://localhost:27017"
    database: "usersDevices"
    tls:
      caFile: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile:  "/secrets/public/cert.crt"
      useSystemCAPool: false
